### ISSUE TITLE
Model and temperature "skip" not working (it actually works, but doesn't look right)

### ISSUE THREAD

**Issue by pirone2** [frowo/AIDungeon#6]
If the config options for skipping the model and temperature setting when starting a story are active, the game just hangs after choosing your name/starting prompt.

**Comment by pirone2** [comment]
What's actually happening, is that it doesn't give you an "Initializing AI Dungeon" output right after you make your choice. This combined with the wrong tensorflow version, made it look like it hanged when it was just loading for a really long time without telling you.
With tensorflow 1.15.0, it takes the input and doesn't say anything, but if you wait for a bit it gives you the "Generating story..." output and shortly after the game begins.

Just make it say the "Initializing AI Dungeon" after choosing the name/starting prompt and it won't look like it's broken.

**Comment by frowo** [comment]
Gonna fix that

**Comment by frowo** [comment]
0f4534d8b7127a88e8a3deb502daf8830825f8a2 added a line telling the player it's working

**Comment by frowo** [comment]
weird, it's still happening, reopening

**Comment by frowo** [comment]
2e00ddd4c0975110901ba30d68285b96c9e2bf65 nevermind, I was just a big brainlet
